# Generated by Django 4.1 on 2022-09-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'default_manager_name': 'objects'},
        ),
    ]
